{% set name = "rich-rst" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a1196fdddf1e364b02ec68a05e8ff8f6914fee10fbca2e6b6735f166bb0da8d4

build:
  number: 0
  script_env: PYTHONUTF8=1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - rich >=12.0.0
    - docutils

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - rich_rst

about:
  home: https://rich-rst.readthedocs.io
  summary: A reStructuredText renderer for rich
  keywords: python cli sphinx python3 restructuredtext rich rst docutils command-line-interface
  dev_url: https://github.com/wasi-master/rich-rst
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
